name: lint

on: [ pull_request, push ]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade vulture # tox
      - run: bandit -x "migrations,squashed_migrations" -r apps/ || true
      - run: vulture || true
      - run: black --check apps/ || true
      - run: codespell --quiet-level=2 || true  # --ignore-words-list="" --skip=""
      - run: flake8 apps/
      - run: isort --check-only apps/ || true
      # - run: tox
      - run: pip install -r requirements/requirements.txt || true
      - run: mypy apps/
      - run: pytest apps/ || true
      - run: pytest --doctest-modules apps/ || true
      - run: shopt -s globstar && pyupgrade --py39-plus **/*.py || true
