name: lint

on: [ pull_request, push ]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      # - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade vulture # tox
      - run: pip install -r requirements/requirements-test.txt
      - run: bandit -x "migrations,squashed_migrations" -r django_diagnostic/ || true
      - run: vulture || true
      - run: black --check django_diagnostic/ || true
      - run: codespell --quiet-level=2 || true  # --ignore-words-list="" --skip=""
      - run: flake8 django_diagnostic/
      - run: isort --check-only django_diagnostic/ || true
      # - run: tox
      - run: pip install -r requirements/requirements.txt || true
      - run: mypy django_diagnostic/
      - run: pytest django_diagnostic/ || true
      - run: pytest --doctest-modules django_diagnostic/ || true
      - run: shopt -s globstar && pyupgrade --py39-plus **/*.py || true
