name: lint

on: [ pull_request, push ]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-preview: true
      - run: poetry --version
      - run: poetry install --only linters,tests,types
      - run: shopt -s globstar && poetry run pyupgrade --py39-plus **/*.py
      - run: shopt -s globstar && poetry run django-upgrade --target-version 4.1 **/*.py
      - run: poetry run bandit -r django_diagnostic/ -c ./pyproject.toml
      - run: poetry run vulture
      - run: poetry run black --check django_diagnostic/
      - run: poetry run codespell ./django_diagnostic/
      - run: poetry run flake8 django_diagnostic/ --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: poetry run isort --check-only --profile black django_diagnostic/
      # - run: tox
      - run: poetry install
      - run: poetry run mypy django_diagnostic/
      - run: poetry run pytest django_diagnostic/ || true
      - run: poetry run pytest --doctest-modules django_diagnostic/ || true
